[build]
functions = "functions/"
publish = "dist/"
command = "export ELM_HOME=\"$NETLIFY_BUILD_BASE/cache/elm\" && npm install &&  npx travelm-agency --elm_path=src/I18n.elm --json_path=public/i18n translations && npm run build"

[dev]
command = "npm start"
targetPort = 1234
autoLaunch = true
framework = "#custom"

[functions]
node_bundler = "esbuild"
included_files = [
  "public/**",

  "content/termsconditions.md",
  "content/en/termsconditions.md",
  "content/es/termsconditions.md",
  "content/de/termsconditions.md",
  "content/pt/termsconditions.md",
  "content/it/termsconditions.md",
  "content/fr/termsconditions.md",

  "content/privacypolicy.md",
  "content/en/privacypolicy.md",
  "content/es/privacypolicy.md",
  "content/de/privacypolicy.md",
  "content/pt/privacypolicy.md",
  "content/it/privacypolicy.md",
  "content/fr/privacypolicy.md",

  "content/review.md",
  "content/en/review.md",
  "content/es/review.md",
  "content/de/review.md",
  "content/pt/review.md",
  "content/it/review.md",
  "content/fr/review.md",

  "content/partners.md",
  "content/en/partners.md",
  "content/es/partners.md",
  "content/de/partners.md",
  "content/pt/partners.md",
  "content/it/partners.md",
  "content/fr/partners.md",

  "content/completeregistration.md",
  "content/en/completeregistration.md",
  "content/es/completeregistration.md",
  "content/de/completeregistration.md",
  "content/pt/completeregistration.md",
  "content/it/completeregistration.md",
  "content/fr/completeregistration.md",

  "content/accommodation.md",
  "content/en/accommodation.md",
  "content/es/accommodation.md",
  "content/de/accommodation.md",
  "content/pt/accommodation.md",
  "content/it/accommodation.md",
  "content/fr/accommodation.md",

  "content/hosts.md",
  "content/en/hosts.md",
  "content/es/hosts.md",
  "content/de/hosts.md",
  "content/pt/hosts.md",
  "content/it/hosts.md",
  "content/fr/hosts.md",

  "content/support.md",
  "content/en/support.md",
  "content/es/support.md",
  "content/de/support.md",
  "content/pt/support.md",
  "content/it/support.md",
  "content/fr/support.md",

  "content/howitworks.md",
  "content/en/howitworks.md",
  "content/es/howitworks.md",
  "content/de/howitworks.md",
  "content/pt/howitworks.md",
  "content/it/howitworks.md",
  "content/fr/howitworks.md",

  "content/services/halfboard.md",
  "content/en/services/halfboard.md",
  "content/es/services/halfboard.md",
  "content/de/services/halfboard.md",
  "content/pt/services/halfboard.md",
  "content/it/services/halfboard.md",
  "content/fr/services/halfboard.md",

  "content/services/hostels.md",
  "content/en/services/hostels.md",
  "content/es/services/hostels.md",
  "content/de/services/hostels.md",
  "content/pt/services/hostels.md",
  "content/it/services/hostels.md",
  "content/fr/services/hostels.md",

  "content/services/selfcatering.md",
  "content/en/services/selfcatering.md",
  "content/es/services/selfcatering.md",
  "content/de/services/selfcatering.md",
  "content/pt/services/selfcatering.md",
  "content/it/services/selfcatering.md",
  "content/fr/services/selfcatering.md",

  "content/about/default.md",
  "content/about/en/default.md",
  "content/about/es/default.md",
  "content/about/de/default.md",
  "content/about/pt/default.md",
  "content/about/it/default.md",
  "content/about/fr/default.md",


  "content/members/juan.md",
  "content/members/en/juan.md",
  "content/members/es/juan.md",
  "content/members/de/juan.md",
  "content/members/pt/juan.md",
  "content/members/it/juan.md",
  "content/members/fr/juan.md",

  "content/members/leo.md",
  "content/members/en/leo.md",
  "content/members/es/leo.md",
  "content/members/de/leo.md",
  "content/members/pt/leo.md",
  "content/members/it/leo.md",
  "content/members/fr/leo.md",

  "Comismsh.ttf",
  "functions/fonts/Comismsh.ttf",
]

[[redirects]]
  from = "/*/"
  to = "/:splat"
  status = 301
  force = true
